# Default configuration for OminousChestLock

lockpicks:
  pick-limit-min: 2
  pick-limit-max: 5
  rusty:
    normal-key-chance: 0.05
    open-chance: 0.1
    damage: 1.0
    break-chance: 0.5
    recipe:
      - COPPER_INGOT
      - TRIPWIRE_HOOK
      - STICK
  normal:
    normal-key-chance: 0.15
    open-chance: 0.25
    damage: 2.0
    break-chance: 0.3
    recipe:
      - IRON_INGOT
      - TRIPWIRE_HOOK
      - BREEZE_ROD
  silence:
    open-chance: 0.35
    damage: 3.0
    break-chance: 0.1
    penalty-reset-ms: 900000 # 15 minutes
    smithing:
      template: SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE
      base: normal_pick
      addition: ECHO_SHARD
  lodestone:
    open-chance: 0.2
    damage: 1.5
    break-chance: 0.2
    recipe:
      - IRON_INGOT
      - TRIPWIRE_HOOK
      - LODESTONE
  lockout-scope: "chest" # Can be "chest", "player", "global"
  enabled: true

keys:
  allow-normal: true # Allow regular trial keys to be used as lock keys (no consumption)

logging:
  level: 1 # 0 for minimal, 1 for info, 2 for debug